### ISSUE TITLE
[ fetch characters ] DATA LAYER - TASK:03

### ISSUE THREAD

**Issue by rodrigoliveirac** [rodrigoliveirac/MyMarvelComics#5]
## TASK REQUIREMENTS

- [x] Characters Repository
- [x] Paging - Fetch Characters from GET characters
- [x] Paging - Fetch Comics from GET comics

### #BONUS 
 
- [x] Read - Character Details - Service
- [x] Read - Comic Details - Service
      
###  Unit Tests - System Behavior
 - [ ]  Repository
 - [x]  PagingRemoteMediator
 - [x]  Read Character - Service
 - [x]  Read Comic - Service
