### ISSUE TITLE
[ fetch characters ] UI LAYER - TASK:04

### ISSUE THREAD

**Issue by rodrigoliveirac** [rodrigoliveirac/MyMarvelComics#8]
## TASK REQUIREMENTS

- [x] App Theme
- [x] Characters Screen
- [x] Characters ViewModel
- [x] Character Details Screen
- [x] Character Details ViewModel
- [x] Navigation from Characters to CharactersDetails 
- [x] Mark as favorite
- [x] Mark as unfavorite
      
###  Unit Tests - System Behavior
 - [ ]  Ui tests
 - [ ]  ViewModel tests
 - [ ]  Navigation Tests
